-- 1. SERVER AUDIT
USE master;
GO

IF EXISTS (SELECT * FROM sys.server_audits WHERE name = 'Audit_RateMyProfessor')
BEGIN
    ALTER SERVER AUDIT Audit_RateMyProfessor WITH (STATE = OFF);
    DROP SERVER AUDIT Audit_RateMyProfessor;
END
GO

CREATE SERVER AUDIT Audit_RateMyProfessor
TO FILE (
    FILEPATH = 'C:\SQLAudit\',
    MAXSIZE = 100 MB,
    MAX_ROLLOVER_FILES = 10
);
GO

ALTER SERVER AUDIT Audit_RateMyProfessor WITH (STATE = ON);
GO

-- 2. SERVER AUDIT SPECIFICATION
USE master;
GO

IF EXISTS (SELECT * FROM sys.server_audit_specifications WHERE name = 'AuditServidor_RMP')
BEGIN
    ALTER SERVER AUDIT SPECIFICATION AuditServidor_RMP WITH (STATE = OFF);
    DROP SERVER AUDIT SPECIFICATION AuditServidor_RMP;
END
GO

CREATE SERVER AUDIT SPECIFICATION AuditServidor_RMP
FOR SERVER AUDIT Audit_RateMyProfessor
ADD (FAILED_LOGIN_GROUP),
ADD (SUCCESSFUL_LOGIN_GROUP);
GO

ALTER SERVER AUDIT SPECIFICATION AuditServidor_RMP WITH (STATE = ON);
GO

-- 3. DATABASE AUDIT SPECIFICATION
USE RateMyProfessorDB;
GO

IF EXISTS (SELECT * FROM sys.database_audit_specifications WHERE name = 'AuditBD_RMP')
BEGIN
    ALTER DATABASE AUDIT SPECIFICATION AuditBD_RMP WITH (STATE = OFF);
    DROP DATABASE AUDIT SPECIFICATION AuditBD_RMP;
END
GO

CREATE DATABASE AUDIT SPECIFICATION AuditBD_RMP
FOR SERVER AUDIT Audit_RateMyProfessor
ADD (INSERT ON dbo.Evaluaciones BY PUBLIC),
ADD (UPDATE ON dbo.Profesores BY PUBLIC),
ADD (DELETE ON dbo.Evaluaciones BY PUBLIC);
GO

ALTER DATABASE AUDIT SPECIFICATION AuditBD_RMP WITH (STATE = ON);
GO